services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      Psr\Cache\CacheItemPoolInterface: '@cache'
      $environment: '%kernel.environment%'

  App\:
    resource: '../src/*'
    exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller/*'
    public: true
    tags: ['controller.service_arguments', 'app.controller']

  App\Security\Voter\:
    resource: '../src/Security/Voter/*'
    tags: ['app.security.voter']

  App\Middleware\:
    resource: '../src/Middleware/*'
    exclude: '../src/Middleware/{Router.php}'

  App\Middleware\Router:
    arguments: [!tagged app.controller]

  # ---------------

  http_kernel:
    class: Symfony\Component\HttpKernel\HttpKernel
    public: true
    arguments:
      - '@Symfony\Component\EventDispatcher\EventDispatcherInterface'
      - '@Symfony\Component\HttpKernel\Controller\ControllerResolver'

  Symfony\Component\HttpKernel\Controller\ControllerResolver: ~


  # ---------------

  cache:
    alias: cache.filesystem

  cache.void:
    class: Symfony\Component\Cache\Adapter\NullAdapter

  cache.filesystem:
    class: Symfony\Component\Cache\Adapter\FilesystemAdapter
    arguments: ['ns', 3600, '%kernel.project_dir%/var/cache/%kernel.environment%/fs']

  App\Middleware\SecurityVoters:
    public: true
    arguments: [!tagged app.security.voter]

  App\DataCollector\CacheDataCollector:
    decorates: 'cache'
    arguments: ['@App\DataCollector\CacheDataCollector.inner']

  Symfony\Component\EventDispatcher\EventDispatcher:
    public: true

  Symfony\Component\EventDispatcher\EventDispatcherInterface:
    alias: Symfony\Component\EventDispatcher\EventDispatcher
    public: true